[package]
name = "project-10-19"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.crossterm]
version = "0.25"
features = ["event-stream"] 